# Generated by Django 3.0.2 on 2020-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0007_room_lender_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
