# Generated by Django 3.0.2 on 2020-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submission', '0002_submission_numberofrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='NumberOfRooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
