# Generated by Django 3.0.2 on 2020-08-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_room_date'),
        ('Submission', '0003_auto_20200820_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='NumberOfRooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_flat', to='Rooms.room'),
        ),
    ]
